# from https://github.com/pestrada/android-tdd-playground/blob/master/.travis.yml
# for help http://docs.travis-ci.com/user/customizing-the-build/
# for android specific help http://docs.travis-ci.com/user/languages/android/

language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-18

android:
  components:
    - build-tools-21.0.1

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew connectedCheck

# http://docs.travis-ci.com/user/languages/android/#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/