# from https://github.com/pestrada/android-tdd-playground/blob/master/.travis.yml
# for help http://docs.travis-ci.com/user/customizing-the-build/
# for android specific help http://docs.travis-ci.com/user/languages/android/
# to validate if script is valid try at http://lint.travis-ci.org/

language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-18

# getting android builds tools to work 
# taken from Eugen Martynov http://stackoverflow.com/questions/21055966/how-should-i-configure-travis-ci-for-an-android-library
before_install:
  - chmod +x gradlew
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
  - tar xzf android-sdk_r24.4.1-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # install android build tools
  - wget https://dl-ssl.google.com/android/repository/build-tools_r21.0.1-linux.zip
  - unzip build-tools_r21.0.1-linux.zip -d $ANDROID_HOME
  - mkdir -p $ANDROID_HOME/build-tools/
  - mv $ANDROID_HOME/android-5.0 $ANDROID_HOME/build-tools/21.0.1
  # Install required components.
  - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
  - echo yes | android update sdk --filter android-18 --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
  - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

install:
  - true
    
android:
  components:
    - build-tools-21.0.1
    
before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
  
script: 
  - ./gradlew assembleDebug
